# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0002_auto_20190114_0821'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('description', tinymce.models.HTMLField()),
            ],
        ),
    ]
