# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0003_business'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=75)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField(max_length=50)),
            ],
        ),
    ]
