# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0005_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighborhood_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='location',
        ),
    ]
