# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0006_auto_20190114_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='neighbour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood'),
        ),
        migrations.AddField(
            model_name='notification',
            name='neighbour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood'),
        ),
        migrations.AddField(
            model_name='profile',
            name='neighbour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='neighborhood.Neighborhood'),
        ),
    ]
