# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-14 13:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborhood', '0007_auto_20190114_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='neighbour',
            new_name='neighbourhood',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='neighbour',
            new_name='neighbourhood',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='neighbour',
            new_name='neighbourhood',
        ),
    ]
